### ISSUE TITLE
Some initial comments

### ISSUE THREAD

**Issue by timj** [lsst/rtn-029#1]
> Note however that for this command to work the default datastore template was modified to replace detector.full_name by detector.

What was the error message? It might indicate that the import is not using a fully-expanded DatasetRef. If the error message comes from the export I am very confused since datastore isn't writing anything during export. We should fix this -- can you please file a ticket. 

> we use a seed configuration file

The datastore entry in there shouldn't be necessary -- FileDatastore is the default. Doesn't hurt to include it.
Normally we don't burn the registry password into the configuration file so we may want to note that this is done for convenience for testing with trusted users.

> importing calibration data needs to be performed before registering instruments 

We should fix this as well. It's now possible for the database inserts to use a different API that compares what is there already with what is being inserted and to not complain if they are identical. I think the dimensions inserts for import can be changed to use that API (much like the instrument registration was changed to allow it to be run multiple times -- to support updates to filter lists). cc/ @TallJimbo 

> Do we also need to register instrument lsst.obs.lsst.LsstCamPhoSim ?

This is extremely confusing. I don't understand why there is anything about PhoSim involved at all or why it would make a difference. The error message there is complaining that imsim instrument name already exists. I'm going to have to reproduce these initial steps to try to work out what's going on.

> We create a chained collection with the Python code below

Probably much easier to use the `butler collection-chain` command for this.

**Comment by TallJimbo** [comment]
> If the error message comes from the export I am very confused since datastore isn't writing anything during export.

`Datastore.export` does construct paths and use filename templates, for some transfer modes; you can tell it to put links or copies in the export directory.  A traceback would be super helpful in tracking this down; I agree that it sounds like it's a failure to expand data IDs, but there are a lot of places that could be.

> It's now possible for the database inserts to use a different API that compares what is there already with what is being inserted and to not complain if they are identical. I think the dimensions inserts for import can be changed to use that API (much like the instrument registration was changed to allow it to be run multiple times -- to support updates to filter lists).

Afraid it's not quite that simple - we have three low-level APIs we can use for dimension records:

- `insertDimensionData`, `replace=False`: vectorized, fails if any record already exists;
- `insertDimensionData`, `replace=True`, vectorized, replaces any existing record without any checking;
- `syncDimensionData`: not vectorized, inserts only if equivalent record does not exist, raises only if existing record is not equivalent.

So we could propagate these options to `Butler.import_`, but we can't afford to do all imports with a non-vectorized API like `syncDimensionData`; we'd need to limit that to dimensions with at most a few hundred entries (e.g. `instrument`, `detector`, filters), and "replace everything" should probably be a use-at-your-own-risk admin-level option in `Butler.import_`, if we put it there at all.

That said, in this particular case,

> importing calibration data needs to be performed before registering instruments

If I'm guessing correctly what's going on here, I suspect a better solution is to use something like
```
skip_dimensions=["instrument", "detector", "physical_filter", "band"]
```
in the call to `Butler.import_`.

**Comment by timj** [comment]
> skip_dimensions=["instrument", "detector", "physical_filter", "band"]

That is also available from the `butler import` command line.

**Comment by airnandez** [comment]
Thanks @timj from your comments. Apologies I had not responded earlier since I only see them today: somehow I didn't get a notification by github of the existence of this issue.

> > Note however that for this command to work the default datastore template was modified to replace detector.full_name by detector.

> What was the error message? It might indicate that the import is not using a fully-expanded DatasetRef. If the error message comes from the export I am very confused since datastore isn't writing anything during export. We should fix this -- can you please file a ticket.

I suggest we continue the discussion specific to the issue of exporting/importing calibration data via [DM-33091](https://jira.lsstcorp.org/browse/DM-33091) so to collect the relevant information in a single place.

I will respond to your comments on improving the note itself in this github issue below.

**Comment by timj** [comment]
I completely forgot about the existence of DM-33091 when I read the comment about exporting. Could you put the ticket number in a footnote in the document so we can remember the issue is being tracked?

**Comment by airnandez** [comment]
> The datastore entry in there shouldn't be necessary -- FileDatastore is the default. Doesn't hurt to include it.
Normally we don't burn the registry password into the configuration file so we may want to note that this is done for convenience for testing with trusted users.

Fixed. See https://rtn-029.lsst.io/#create-an-empty-repository

**Comment by airnandez** [comment]
> > We create a chained collection with the Python code below

> Probably much easier to use the butler collection-chain command for this.

Fixed. See https://rtn-029.lsst.io/#create-collections

**Comment by airnandez** [comment]
> Could you put the ticket number in a footnote in the document so we can remember the issue is being tracked?

Done, although not it a footnote. See https://rtn-029.lsst.io/#calibration-data

**Comment by airnandez** [comment]
>  I suspect a better solution is to use something like
> `skip_dimensions=["instrument", "detector", "physical_filter", "band"]`
> That is also available from the butler import command line.

Fixed. We now use `butler import --skip-dimensions instrument,detector,physical_filter,band ...` to import calibration data.

See https://rtn-029.lsst.io/#import-calibration-data

**Comment by airnandez** [comment]
I think we addressed this in the current version of the note. I am closing this issue.
